name: flouter
description: A Flutter router that is based navigator 2.0 API and use Regexp to do path matching.
version: 0.2.0-nullsafety.1
repository: https://github.com/Kleak/flouter/tree/nullsafety

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety.6
  provider: ^5.0.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
