name: flouter
description: An easy router for Flutter with navigator 2.0
version: 0.1.0
author: Kevin Segaud <me@kleak.dev>
repository: https://github.com/Kleak/flouter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
