name: flouter
description: A Flutter router that is based navigator 2.0 API and use Regexp to do path matching.
version: 0.1.1
repository: https://github.com/Kleak/flouter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
