name: Test Flouter on main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: stable

      - name: Format for pub score
        run: flutter format -n --set-exit-if-changed .

      - name: Build deps
        run: flutter pub get

      - name: Run test
        run: flutter test
